### PR TITLE
Upgrade to 7.8~ynh1

### LINKED ISSUE #84: Hubzilla 7.2 updating via util/udall
Hi there,

is it save to update Hubzilla via "util/udall"? It seems there are some security fixes on the way (7.2 release) and it would be fine to have those integrated.

Regards,

Stefan

### LINKED ISSUE #90: UPGRADE faild by installing testing branch HZ -7.2
by trying to install the testing branch 7.2 i got this kind of errors:

```
2920624 DEBUG               Depends: php8.1-readline but it is not going to be installed
2920624 DEBUG               Depends: libpcre2-8-0 (>= 10.38) but 10.32-5 is to be installed
2920625 DEBUG               Depends: libsodium23 (>= 1.0.18) but 1.0.17-1 is to be installed
2920626 DEBUG  php8.1-fpm : Depends: php8.1-opcache but it is not going to be installed
2920627 DEBUG               Depends: libpcre2-8-0 (>= 10.38) but 10.32-5 is to be installed
2920627 DEBUG               Depends: libsodium23 (>= 1.0.18) but 1.0.17-1 is to be installed
2920628 DEBUG  php8.1-imagick : Breaks: php-imagick (< 3.6.0-4+0~20220117.35+debian10~1.gbp149f82~)
2920629 DEBUG  php8.1-zip : Depends: libzip4 (>= 1.7.0) but 1.5.1-4 is to be installed
2920629 DEBUG + ynh_die '--message=Unable to install dependencies'
2920630 DEBUG + local legacy_args=mc
2920630 DEBUG + args_array=([m]=message= [c]=ret_code=)
2920631 DEBUG + local -A args_array
2920632 DEBUG + local message
2920632 DEBUG + local ret_code
2920633 DEBUG + ynh_handle_getopts_args '--message=Unable to install dependencies'
2920634 DEBUG + set +o xtrace
2920689 DEBUG + ret_code=1
2920689 DEBUG + echo 'Unable to install dependencies'
2920690 DEBUG Unable to install dependencies
2920691 DEBUG + exit 1
2920691 DEBUG + ynh_exit_properly
2920692 DEBUG + local exit_code=1
2920692 DEBUG + rm -rf /var/cache/yunohost/download/
2920694 DEBUG + trap '' EXIT']'
                                                                                                                    
2920694 DEBUG + set +o errexit
2920695 DEBUG + set +o nounset
2920696 DEBUG + sleep 0.5
2921199 DEBUG + type -t ynh_clean_setup
2921200 DEBUG + ynh_clean_setup
2921201 DEBUG + ynh_restore_upgradebackup
2921201 DEBUG + ynh_print_err '--message=Upgrade failed.'
2921202 DEBUG + local legacy_args=m
2921203 DEBUG + local -A args_arraysage=)
                                                                                                                    
2921204 DEBUG + local message
2921205 DEBUG + ynh_handle_getopts_args '--message=Upgrade failed.'
2921205 DEBUG + set +o xtrace
2921237 DEBUG + ynh_print_log '[Error] Upgrade failed.'
2921238 DEBUG + echo -e '[Error] Upgrade failed.'
2921238 DEBUG [Error] Upgrade failed.
2921239 DEBUG + local app_bck=hubzilla
2921239 DEBUG + NO_BACKUP_UPGRADE=0
```

### LINKED ISSUE #106: Update 7.6.1 fails
on my two different servers HZ is not working since the last updates 

Hubzilla is up but 
- no old posts are shown
- no new post are received by the servers 
- no new items can be created

if i turn on ` ini_set('display_errors', '1');` in `/var/www/hubzilla/.htconfig.php`
several errors are shown 

e.g. on page /network

```
Warning: Undefined variable $a in /var/www/hubzilla/Zotlabs/Module/Network.php on line 211

Warning: Undefined array key "htmlhead" in /var/www/hubzilla/include/conversation.php on line 1434

Warning: Undefined array key "template" in /var/www/hubzilla/addon/gallery/gallery.php on line 78

Warning: Undefined array key "deleted" in /var/www/hubzilla/Zotlabs/Lib/Apps.php on line 524
```

and on page /item 

```
`Warning: Undefined array key "conv_mode" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 322

Warning: Undefined array key "group_allow" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

144

Warning: Undefined array key "group_allow" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

145

Warning: Undefined array key "contact_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

146

Warning: Undefined array key "contact_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 

147

Warning: Undefined array key "group_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 148

Warning: Undefined array key "group_deny" in /var/www/hubzilla/Zotlabs/Access/AccessList.php on line 149

Warning: Undefined array key "verb" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 725

Warning: Undefined array key "attachment" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 729

Warning: Undefined array key "type" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 960

Warning: Undefined array key "type" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 960

Warning: Undefined variable $mid in /var/www/hubzilla/Zotlabs/Module/Item.php on line 989

Warning: Undefined array key "obj" in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1048

Warning: Undefined variable $item_starred in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1089

Warning: Undefined variable $item_uplink in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1090

Warning: Undefined variable $item_notshown in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1092

Warning: Undefined variable $item_nsfw in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1093

Warning: Undefined variable $item_relay in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1094

Warning: Undefined variable $item_mentionsme in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1095

Warning: Undefined variable $item_verified in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1098

Warning: Undefined variable $item_retained in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1099

Warning: Undefined variable $item_rss in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1100

Warning: Undefined variable $item_deleted in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1101

Warning: Undefined variable $item_hidden in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1102

Warning: Undefined variable $item_unpublished in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1103

Warning: Undefined variable $item_delayed in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1104

Warning: Undefined variable $item_pending_remove in /var/www/hubzilla/Zotlabs/Module/Item.php on line 

1105

Warning: Undefined variable $item_blocked in /var/www/hubzilla/Zotlabs/Module/Item.php on line 1106

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/wppost/wppost.php on line 55

Warning: Trying to access array offset on value of type bool in /var/www/hubzilla/extend/addon/dm42-

addons/forum/forum.php on line 815

Warning: Undefined array key "target_item" in /var/www/hubzilla/addon/diaspora/diaspora.php on line 1031

Warning: Trying to access array offset on value of type null in 

/var/www/hubzilla/addon/diaspora/diaspora.php on line 1031

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/libertree/libertree.php on line 50

Warning: Undefined array key "edit" in /var/www/hubzilla/addon/pumpio/pumpio.php on line 175`
```

Don´t know - @ericgaspar does this help to identify the problem?

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #106*
- *Fix #90*
- *Fix #84*

## Solution

- *Upgrade to 7.8~ynh1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by rocky-III** [comment]
@yalh76 now i also updated the second hub and i notices that all changes i made for e.g. the theme are gone and overwritten  by the new installation... I think that happen with the changes you did before you did the last fix... can you redo this changes? because is is quid incontinent if the adoption i made have to be redone by every update - 

that would be very nice - thanks.

**Comment by yalh76** [comment]
> @yalh76 now i also updated the second hub and i notices that all changes i made for e.g. the theme are gone and overwritten by the new installation... I think that happen with the changes you did before you did the last fix... can you redo this changes? because is is quid incontinent if the adoption i made have to be redone by every update -
> 
> that would be very nice - thanks.

where are stored the themes ?
where are the other changes you have done ?

**Comment by rocky-III** [comment]
actually i don't remember  all the changes i did in the last years  -  but they are all located in the folder /hubzilla/view  and its sub folders like de-de, tpl, pdl,  php and theme

**Comment by yalh76** [comment]
If the change are made on /view, they will be overwritten by hubzilla sources ...

**Comment by yalh76** [comment]
I've removed the cleanup of previous sources, but not sure it will enough for the changes you made

**Comment by rocky-III** [comment]
Ok i restore the backup right now an try again your new version...   

the changes i made are old and were not overwritten by updates i did before HZ 7.4

**Comment by rocky-III** [comment]
i had also installed some extra addons which are not in the official repor in the folder hubzilla/extend/

**Comment by yalh76** [comment]
!testme

let me know if it's better now

**Comment by rocky-III** [comment]
NO -not working
by this update my  changes seam to be overwritten :-) 
but the curl problem is again there...
blank pages - not working installation

so it has to be something in between :-)

**Comment by yalh76** [comment]
> NO -not working by this update my changes seam to be NOT overwritten :-) but the curl problem is again there... blank pages - not working installation
> 
> so it has to be something in between :-)

The issue is: you have old hubzilla files in the source files that cause that curl problem.

You can look at the only change I made => https://github.com/YunoHost-Apps/hubzilla_ynh/pull/113/commits/0c3683e47087354d09196ee9f0e6aae5e4b65d03

So I think it's time for you to forget the custom modifications you made in the source code or to learn to make it in a more recent version of hubzilla

**Comment by rocky-III** [comment]
OK - i saved some folders now - i can restore manually this things now ... hope i don't have to do it by all upcoming updates in the future over and over again - what do you think?

**Comment by rocky-III** [comment]
may i try again?

**Comment by yalh76** [comment]
I let you go. I didn't roll-rollbacked

But if you still have curl issues, it comes or from the old hubzilla files kept during the upgrade or from your customised files.

**Comment by rocky-III** [comment]
> I didn't roll-rollbacked

so you did not redo the changes you did here?  

https://github.com/YunoHost-Apps/hubzilla_ynh/commit/0c3683e47087354d09196ee9f0e6aae5e4b65d03

> it comes or from the old hubzilla files kept during the upgrade or from your customised files.
don't  think that the problems come for the files in the /view folder - but maybe they do ... so i backed them up.... 

ready for a more recent version of hubzilla

**Pull request merged**
