### PR TITLE
Upgrade is broken

### PR DESCRIPTION
**Pull request by anmol26s**
## Upgrade is failing

- *Upgrade fails because random_string is not get before calling it*

## Solution

- *get random_string before calling it*

## PR Status

- [ X ] Code finished and ready to be reviewed/tested
- [ X ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by anmol26s** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by orhtej2** [comment]
Isn't this the right/common way of doing this check? https://github.com/YunoHost-Apps/element_ynh/blob/633cb1d6accbd7fda57d599e7d8ef4c8297723b1/scripts/upgrade#L24

**Comment by anmol26s** [comment]
@orhtej2 
Maybe yes for the Element app, but how do we know that here if reandom_string is set inside settings? We need to fetch it to check it, otherwise there is no point in having this check.
In Element it is fetched from the manifest. Here, if we keep it like this, it will always go inside the block because the radom_string is not declared inside the environment.  And every time it will set a new random_string, which I think is not what we want.
Do you have a better way?

**Comment by orhtej2** [comment]
You're loading `random_string` from app settings and these per [packaging v2](https://yunohost.org/en/packaging v2) are now automatically loaded. What pointed stanza in Element script does it is checks if the variable exists, because if it does then the setting is already set.

**Comment by anmol26s** [comment]
!testme

**Pull request closed without merging**
