### PR TITLE
Upgrade to 7.8~ynh1

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Upgrade to 7.8~ynh1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by rocky-III** [comment]
Whooo... i just tried it by

`sudo yunohost app upgrade hubzilla -u https://github.com/YunoHost-Apps/hubzilla_ynh/tree/upgrade`

and this upgrade is the first since a long time which worked on my raspi installation... 

so now after a long time my Yunohost HZ Installation is update again :-)

**Comment by rocky-III** [comment]
NO NO NO 
after looking more closely... this updates is again NO working for me

the page /network  does work now :-)

BUT

on the page  /channel/name I see just a black page and this kind of warnings

```
Warning: Undefined variable $Pojectname in /var/www/hubzilla/view/de-de/hstrings.php on line 1835

Warning: Undefined array key "children" in /var/www/hubzilla/addon/superblock/superblock.php on line 111

Warning: Undefined variable $arr in /var/www/hubzilla/addon/nsfw/nsfw.php on line 77

Warning: Undefined array key "term" in /var/www/hubzilla/Zotlabs/Lib/ThreadItem.php on line 301

Warning: Undefined array key "superblock" in /var/www/hubzilla/addon/superblock/superblock.php on line 341

atal error: Uncaught Error: Call to undefined function curl_init() in /var/www/hubzilla/include/network.php:54 Stack trace: #0 /var/www/hubzilla/include/oembed.php(281): z_fetch_url() #1 /var/www/hubzilla/include/bbcode.php(77): oembed_fetch_url() #2 [internal function]: tryoembed() #3 /var/www/hubzilla/include/bbcode.php(1271): preg_replace_callback() #4 /var/www/hubzilla/include/text.php(2076): bbcode() #5 /var/www/hubzilla/include/text.php(1786): prepare_text() #6 /var/www/hubzilla/Zotlabs/Lib/ThreadItem.php(352): prepare_body() #7 /var/www/hubzilla/Zotlabs/Lib/ThreadStream.php(223): Zotlabs\Lib\ThreadItem->get_template_data() #8 /var/www/hubzilla/include/conversation.php(921): Zotlabs\Lib\ThreadStream->get_template_data() #9 /var/www/hubzilla/Zotlabs/Module/Channel.php(491): conversation() #10 /var/www/hubzilla/Zotlabs/Web/Router.php(288): Zotlabs\Module\Channel->get() #11 /var/www/hubzilla/Zotlabs/Web/WebServer.php(109): Zotlabs\Web\Router->Dispatch() #12 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run() #13 {main} thrown in /var/www/hubzilla/include/network.php on line 54


```
the Page /admin/  is blank and gives me 

```
Warning: Undefined variable $Pojectname in /var/www/hubzilla/view/de-de/hstrings.php on line 1835

Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/hubzilla/include/network.php:54 Stack trace: #0 /var/www/hubzilla/include/network.php(1744): z_fetch_url() #1 /var/www/hubzilla/Zotlabs/Module/Admin.php(133): get_repository_version() #2 /var/www/hubzilla/Zotlabs/Module/Admin.php(65): Zotlabs\Module\Admin->admin_page_summary() #3 /var/www/hubzilla/Zotlabs/Web/Router.php(288): Zotlabs\Module\Admin->get() #4 /var/www/hubzilla/Zotlabs/Web/WebServer.php(109): Zotlabs\Web\Router->Dispatch() #5 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run() #6 {main} thrown in /var/www/hubzilla/include/network.php on line 54
```


if i try to send an post it will not get delivers - if i look at the delivery report i see this kind of warnings:

```
Warning: Trying to access array offset on value of type null in /var/www/hubzilla/include/nav.php on line 113

Warning: Trying to access array offset on value of type null in /var/www/hubzilla/include/nav.php on line 116

Warning: Trying to access array offset on value of type null in /var/www/hubzilla/include/nav.php on line 279
```


the page   /admin/addons/
gives me:
```
Warning: Undefined array key 1 in /var/www/hubzilla/include/plugin.php on line 561
```

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@rocky-III can you test last version of this branch ?

**Comment by rocky-III** [comment]
thanks @yalh76 for your input and work but this new version has the same problems as the last
i just tried it and it  just does not work

I contacted the mean DEV of HZ and asked him what he things is the problem. He said the warnings are not that relevant - we have to look at the Fatal ERRORS - The errors  point to a not proper working curl he said.

**Comment by yalh76** [comment]
should be fix with last commit

**Comment by rocky-III** [comment]
Thanks -  I will give it a try

**Comment by yalh76** [comment]
!testme

**Comment by rocky-III** [comment]
YES YES YES
@yalh76 YOU DID IT  looks good  - it is working... THANKS

**Pull request merged**
