### PR TITLE
Update upgrade

### PR DESCRIPTION
**Pull request by rocky-III**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
no need of that and there are some errors in you copy/paste

**Comment by yalh76** [comment]
L118, you have  a not needed `fi`

**Comment by rocky-III** [comment]
Ohh Thanks- thanks for telling me ... i just did the concretion

so this will got straight into the master branche... 

my thought was to offer an other update branche for all which are in the same situation as I'm... I know some HZ users who seam to have similar problems to update the YNH HZ installation by the provided script.

**Comment by yalh76** [comment]
so.
Is it better to cleanup all previous sources or to keep them ? I don't understand

**Comment by rocky-III** [comment]
it seams to depending on the installation... 

e.g. extra installed, edited or  used thems should stay

also i had to edit 
/etc/php/7.4/fpm/pool.d/hubzilla.conf

to optimize php on my server... as long there is not an change  which version of PHP is used by the app i would aspect that the edited file will be not overwritten by an update. 

in updates prior 7,4 this uses to work like this...

now the update does not work like you say because of the old files ... so this time i will have overwrite all files in order to update... :-(

**Comment by yalh76** [comment]
> it seams to depending on the installation...
> 
> e.g. extra installed, edited or used thems should stay

ok then, in that case this PR should be closed, because it completly remove previous sources

For the PHP7.4 optimisation, you should do a PR for that to have it for every one

**Comment by rocky-III** [comment]
the needed php optimizing deepens on the server

**Comment by rocky-III** [comment]
@yalh76 did some more investigation. not the files in /view cased the problem but an extra installed addon which is not part of the official repro - 

After deleting this the updated works now :-) 

the file 
/etc/php/8.0/fpm/pool.d/hubzilla.conf

should be edited to optimize php 

the values for 

```
pm.max_children =
pm.start_servers = 
pm.min_spare_servers = 
pm.max_spare_servers = 
```
as discrete here: 
https://chrismoore.ca/2018/10/finding-the-correct-pm-max-children-settings-for-php-fpm/

the lines 
```
php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size] = 50M
```

should be uncommented and edited - otherwise HZ uploads do just work for files with less then 2MB
and
depending of the server hardware also uncommented and edited  this lines:
```
php_admin_value[max_input_time] = 300
php_admin_value[memory_limit] = 256M
```
__

Maybe this infos should go in to YunoHost-Apps/README.md

what do you think?

**Comment by yalh76** [comment]
> @yalh76 did some more investigation. not the files in /view cased the problem but an extra installed addon which is not part of the official repro -
> 
> After deleting this the updated works now :-)
> 
> the file /etc/php/8.0/fpm/pool.d/hubzilla.conf
> 
> should be edited to optimize php
> 
> the values for
> 
> ```
> pm.max_children =
> pm.start_servers = 
> pm.min_spare_servers = 
> pm.max_spare_servers = 
> ```
> 
> as discrete here: https://chrismoore.ca/2018/10/finding-the-correct-pm-max-children-settings-for-php-fpm/
> 
> the lines
> 
> ```
> php_admin_value[upload_max_filesize] = 50M
> php_admin_value[post_max_size] = 50M
> ```
> 
> should be uncommented and edited - otherwise HZ uploads do just work for files with less then 2MB and depending of the server hardware also uncommented and edited this lines:
> 
> ```
> php_admin_value[max_input_time] = 300
> php_admin_value[memory_limit] = 256M
> ```
> 
> __
> 
> Maybe this infos should go in to YunoHost-Apps/README.md
> 
> what do you think?

Why not, i let you do the PR for that ;)

**Pull request closed without merging**
