### PR TITLE
Translation into fr + Mod° of the choice YES/NO  to a bolean choice.

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Comment by frju365** [comment]
Boolean is a better choice for the translations : Yes/No are English words.

**Comment by anaqreon** [comment]
Thank you for the translations. I am merging them into the current manifest file. The boolean type idea is a moot point now, because that setting has been dropped from the list.

**Comment by anmol26s** [comment]
@frju365 
Can you resolve conflicts for the French translation?
Thanks

**Comment by frju365** [comment]
Well, my PR is now useless.

**Pull request closed without merging**
