### PR TITLE
Updated the sources to 2.4

### PR DESCRIPTION
**Pull request by anmol26s**

### CODE REVIEW

**Comment by anaqreon** [comment]
@anmol26s, did you test this on (1) a new installation and/or (2) an update?

**Comment by anmol26s** [comment]
Ok the installation script fails while checking the md5 checksum? @polytan02 need to see why its failing.

**Comment by anmol26s** [comment]
I have removed the .zip from the source_file of the hubzilla and hubzilla-addons. Now the package is working. I have checked the 1. Install script 2. Update script 3. Remove script. 
On update the hubzilla folder from /var/www/hubzilla is removed and then the sources are unzipped in this folder again. Do we need the backup some files from this while update? Where is the user data like pics,wiki,uploaded files,etc saved?

**Comment by anaqreon** [comment]
Thanks for testing further. You probably don't want to remove the web root folder because the "store" folder for example contains member content. It might be sufficient to rsync the source without the delete option so that files are only updated as necessary. I'll have to think about that some more though.

**Comment by anmol26s** [comment]
Ok my bad,it do not get deleted but sources are copied to the folder with the cp command in the update script. It can be changed to rsync if its better scenario. Otherwise looks good to me.

**Comment by anaqreon** [comment]
Great. I'll see if I can test it as well before merging.

**Comment by anaqreon** [comment]
I spun up a virtual machine using the following Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.33.10"
end
```
using
```
vagrant up
vagrant ssh
```
and then I installed the latest YunoHost using the instructions here: <https://yunohost.org/#/install_manually>
```
yunohost --version
yunohost: 2.6.4
yunohost-admin: 2.6.1
moulinette: 2.6.1
ssowat: 2.6.8
```
After creating a YunoHost user account, I installed the Hubzilla package using the GitHub URL: https://github.com/anmol26s/hubzilla-yunohost

The installation was successful.

**Comment by anaqreon** [comment]
I don't see an option to update the app in order to test the update process. How do I do that?

**Comment by anmol26s** [comment]
You have to update from command-line : yunohost app upgrade --verbose -u https://github.com/anmol26s/hubzilla-yunohost  hubzilla

**Comment by anaqreon** [comment]
It looks like the update worked without deleting the channel or photo I had uploaded beforehand. It was strange, however, that the channel profile photo disappeared and had to be reset manually.

**Comment by anmol26s** [comment]
What could be the reason for such a behavior? Do you think rsync instead of cp can help in removing the this issue? Or maybe copying the "data" folder from root on a completely fresh root folder while update would be good? Maybe using git in the script to install and update would be a good idea?

**Comment by anaqreon** [comment]
I don't know what caused that, but it seems like it would be safer to use `rsync -cr` so that only the updates are applied and nothing that is already there is deleted.

**Comment by anmol26s** [comment]
I have updated the sources to 2.4.1 and added cp command to copy the store folder to new sources while updating. Now I can see my data after the running the upgrade script.
If you can check the backup and restore script,it would be great as there is restore issue going on in YunoHost  for the servers not having archivemount. Though the backup script was successful.

**Comment by anaqreon** [comment]
It might be a few days before I can properly test this. If you are confident that things are working properly and want to push the release out, I trust your judgement.

**Comment by anmol26s** [comment]
I am using the same package for my hub since 4 to 5 days. And it is working fine. It has lot of hard work from  @polytan02 too. There may be minor issues with the nginx configuration and testing of backup and restore. But that can be resolved in future as the Yunohost packaging gets more stable. The sources of package are taken from original  Hubzilla Github channel and is checked with checksum, so there should not be a problem of integration of stale sources like before. All looks good, so you can merge the pull request.

**Comment by anmol26s** [comment]
I have updated the package to 2.4.2 and added the ldap integration.

**Comment by anaqreon** [comment]
You said to pull the changes, but then added a bunch of other commits a few hours later! You are on a roll :-) It's good to have at least one person try installing the package from scratch. I can do that in the next few days, or if you have done that and it's fine then we can merge this request and open a new one if you have more improvements to add. What do you think?

**Comment by anmol26s** [comment]
I am testing each commit on [yuno_test ](https://github.com/anmol26s/hubzilla-yunohost/tree/yuno_test) branch first, after the successful running of install, update and remove scripts I merge them to the my [master fork](https://github.com/anmol26s/hubzilla-yunohost) and then send pull request to your [Yunohost main Hubzilla repository](https://github.com/YunoHost-Apps/hubzilla_ynh). So you can be sure of successful running of install ,update and remove scripts. You can wait if you want to check the syntax and commenting of the  scripts. Otherwise you can merge. I will keep doing the to-do's of the package.

**Pull request merged**
